@ParametersAreNonnullByDefault
@FieldsAndMethodsAreNonnullByDefault
package com.refinedmods.refinedstorage.trinkets;

import javax.annotation.ParametersAreNonnullByDefault;

import com.refinedmods.refinedstorage2.api.core.FieldsAndMethodsAreNonnullByDefault;
